### ISSUE TITLE
Kesalahan Nama Sekolah

### ISSUE THREAD

**Issue by Nur47-blip** [ia-toki/ksn-web#6]
Nama sekolah dari Naila Atifa Asrif, Raihan Akbar, Aushaaf Fadhillah Azzah, dan Ahmad Ghozi Fidinillah seharusnya adalah MAN 2 Kota Malang. (Ada perbedaan MAN 2 Malang dengan MAN 2 Kota Malang)

https://ksn.toki.id/statistik/sekolah/3

**Comment by fushar** [comment]
Wah, mohon maaf atas ketidaknyamanannya. Terima kasih atas koreksinya! Sudah diperbaiki.
