### ISSUE TITLE
Kesalahan Sekolah

### ISSUE THREAD

**Issue by yokowasisbima** [ia-toki/ksn-web#8]
Wasis Haryo Sasoko, Propinsi NTB, 2003. Harusnya sekolah SMAN 1 Kota Bima. Also teman2 toki, jaman dulu ada group komunitas khususnya kah ?

**Comment by fushar** [comment]
> Wasis Haryo Sasoko, Propinsi NTB, 2003. Harusnya sekolah SMAN 1 Kota Bima.

Terima kasih atas koreksinya. Sudah diperbaiki!
